name: condaenv
channels:
  - conda-forge
dependencies:
  - keras=2.10.0
  - loguru=0.6.0
  - mkl=2022.1.0
  - numba=0.56.2
  - numpy=1.23.3
  - pandas=1.4.4
  - pip=22.2.2
  - pytest=7.1.3
  - python=3.9.13
  - pytorch-gpu=1.12.1
  - pytorch-lightning=1.7.6
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - tensorflow-gpu=2.10.0
  - tqdm=4.64.1
  - imbalanced-learn==0.10.0
  - matplotlib==3.6.2
  - opacus==1.2.0
  - sdmetrics==0.8.1
  - seaborn==0.12.1
  - pip:
      - flwr[simulation]==1.1.0
      - gower==0.1.2
